**Creation of ndarray**

Write python code to create 3d array in different ways with 15 elements.


In [1]:
import numpy as np


In [2]:
arr = np.array([np.random.randint(1,20,15)], ndmin = 3)           ## Way 1
arr

array([[[12, 12,  6, 11, 16, 12,  6, 19,  8, 19, 10, 14,  9,  3, 16]]])

In [3]:
array = np.array([[[12, 13,  6, 11, 16, 15,  7, 19,  8, 19, 10, 14,  9,  3, 16]]])     ## Way 2
array

array([[[12, 13,  6, 11, 16, 15,  7, 19,  8, 19, 10, 14,  9,  3, 16]]])

In [7]:
ar = np.array([12, 13,  6, 11, 16, 15,  7, 19,  8, 19, 10, 14,  9,  3, 16]).reshape(1,5,3)      ## Way 3
ar

array([[[12, 13,  6],
        [11, 16, 15],
        [ 7, 19,  8],
        [19, 10, 14],
        [ 9,  3, 16]]])

Array Creation: a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.

In [9]:
arr1 = np.array([np.arange(1,13)], ndmin = 4)
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [16]:
array1 = np.array([np.random.random(20)], ndmin = 3)
array1

array([[[0.55987943, 0.68432761, 0.89549126, 0.30740884, 0.83947412,
         0.17015661, 0.72281966, 0.62290453, 0.12417324, 0.29277138,
         0.07061073, 0.51120254, 0.82022954, 0.46010072, 0.1200286 ,
         0.97736656, 0.74566045, 0.79958663, 0.34368994, 0.06669311]]])

Find all attributes of array1 and array2

In [18]:
arr1.dtype

dtype('int32')

In [19]:
arr1.itemsize

4

In [20]:
arr1.nbytes

48

In [21]:
arr1.ndim

4

In [22]:
arr1.size

12

In [23]:
array1.dtype

dtype('float64')

In [24]:
array1.itemsize

8

In [25]:
array1.nbytes

160

In [26]:
arr1.ndim

4

In [27]:
arr1.size

12

Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [28]:
np.mean(arr1)             ## Average of the arr1 is 6.5

6.5

In [29]:
np.median(arr1)          ## Center point of the arr1 is 6.5

6.5

In [30]:
np.std(arr1)             ## Standard Deviation is 3.452052529534663

3.452052529534663

In [31]:
np.var(arr1)            ## Variance is 11.916666666666

11.916666666666666

In [32]:
np.min(arr1)          ## Minimum of the arr1 is 1

1

In [33]:
np.max(arr1)          ## Maximum of the arr1 is 12

12

In [35]:
range1 = np.max(arr1)-np.min(arr1)          ## Range is max - min of array
range1 

11

In [37]:
np.mean(array1)             ## Average of the array1 is 0.5067287751842867

0.5067287751842867

In [38]:
np.median(array1)          ## Center point of the array1 is 0.5355409848506842

0.5355409848506842

In [39]:
np.std(array1)             ## Standard Deviation is 0.29379668479557647

0.29379668479557647

In [41]:
np.var(array1)            ## Variance is 0.0863164919968713

0.0863164919968713

In [42]:
np.min(array1)          ## Minimum of the array1 is 0.06669311057971616

0.06669311057971616

In [44]:
np.max(array1)          ## Maximum of the array1 is 0.9773665567707088

0.9773665567707088

In [45]:
range1 = np.max(array1)-np.min(array1)          ## Range is max - min of array1
range1 

0.9106734461909927

In [55]:
q1 = np.percentile(arr1,25)            ## First Quartile of arr1
q1

3.75

In [56]:
q3 = np.percentile(arr1,75)          ## Third Quartile of arr1
q3

9.25

In [57]:
IQR = q3 - q1                     ## Inter Quartile Range of arr1
IQR

5.5

In [58]:
lower = q1 - (1.5*IQR)            ## Lower limit of arr1
lower

-4.5

In [59]:
upper = q3 + (1.5*IQR)            ## Upper limit of arr1
upper

17.5

In [60]:
arr1[arr1>upper]            ## No value above upper limit which means no outlier on upper side

array([], dtype=int32)

In [61]:
arr1[arr1<lower]          ## No value above lower limit which means no outlier on lower side

array([], dtype=int32)

**Array Slicing and Indexing:**

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [2]:
arr1 =  np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [3]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr1[3]           ## element at index 3 of arr1

73

In [7]:
arr2[2,1]         ## element at row 2, column 1 of arr2

7

In [8]:
arr1[0:5]        ##  the first five elements of arr1

array([ 0, 11, 26, 73, 42])

In [12]:
arr2[1:3,0:2]    ## the subarray of arr2 consisting of the last two rows and the first two columns

array([[3, 4],
       [6, 7]])

In [15]:
arr1[1:8:2]             ##every second element starting from index 1 up to index 7 of arr1.

array([11, 73, 51, 77])

**Data Type Manipulation**

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [37]:
int_array = np.array([1, 2, 3, 4, 5], dtype = 'int16')    ## Default datatype integer is 'int32' hence given 'int16'
int_array

array([1, 2, 3, 4, 5], dtype=int16)

In [46]:
int_array.dtype

dtype('int16')

In [47]:
float_array = np.array([0.1, 0.2, 0.3, 0.4, 0.5]) ## Default datatype float is 'float64' hence has not give any input datatype
float_array

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [48]:
float_array.dtype

dtype('float64')

In [63]:
int_array = np.array(int_array,np.dtype('float32'))       ## Converting in 'float32'

In [64]:
int_array.dtype       

dtype('float32')

In [65]:
int_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [66]:
float_array = np.array(float_array,np.dtype('int32'))    ## Converting in 'int32'

In [67]:
float_array.dtype

dtype('int32')

In [68]:
float_array

array([0, 0, 0, 0, 0])

**Generating Random Numbers:**

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

In [69]:
rand_integers = np.random.randint(0,100,10)
rand_integers

array([83, 86, 70, 54, 81, 51, 59, 91, 77, 94])

In [73]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([ 0.28148356, -0.83739771,  0.71434469, -0.69327845,  0.53465882])

In [75]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[89, 61, 89, 50],
       [56, 64, 65, 70],
       [66, 54, 92, 93],
       [69, 79, 97, 60]])

In [76]:
np.mean(rand_matrix)          ## Average of array 

72.125

In [77]:
np.median(rand_matrix)       ## center value of array

67.5

In [78]:
np.std(rand_matrix)      ## standard Deviation

14.966107543379474

In [79]:
np.var(rand_matrix)       ## Variance

223.984375

In [80]:
range1 = np.max(rand_matrix)-np.min(rand_matrix)          ## Range
range1

47

**IQR for above Array**

In [81]:
Q1 = np.percentile(rand_matrix,25)         ## 25 percent of  Quartile
Q1

60.75

In [82]:
Q3 = np.percentile(rand_matrix,75)        ## 75 ercent of Quartile
Q3

89.0

In [83]:
IQR = Q3-Q1                        ## inter quartile range
IQR

28.25

In [87]:
lower = Q1 - (1.5*IQR)       ## lower limit and there is no value below lower limit
print(lower)
rand_matrix[rand_matrix<lower]

18.375


array([], dtype=int32)

In [88]:
upper = Q3+(1.5*IQR)     ## upper limit and there is no value above upper limit
print(upper)
rand_matrix[rand_matrix>upper]

131.375


array([], dtype=int32)

In [89]:
## There are no outliers as per above array

**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following: 1. How many employees are getting more less than 50000?


Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [90]:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

In [93]:
salaries = np.array(Salaries)
salaries

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [96]:
above = np.sum(salaries>50000)       ## no.of employees above salary 50000
above

25

In [97]:
below = np.sum(salaries<50000)      ## no.of employees below salary 50000
below

5

In [101]:
avg_salary = np.mean(salaries)         ## Average Salary
avg_salary

166169.16666666666

In [98]:
np.median(salaries)             ## Median salary

61699.5

In [111]:
## Mean of the Salary and median of the salary is not equal hence this is not a normal distribution

In [99]:
salary_range = np.max(salaries) - np.min(salaries)      ## Salary range
salary_range

3082388

In [102]:
Q1 = np.percentile(salaries,25)    ## 25% of the salaries
Q1

52963.25

In [104]:
np.sum(salaries<Q1)        ## number of employees with less than 25% salaries

8

In [105]:
Q3 = np.percentile(salaries,75)       ## 75% of the salaries
Q3

84496.5

In [110]:
salaries[(salaries<avg_salary) & (salaries>=Q3)]      ## Salaries between average salary and 75% of salary

array([87877, 85051, 94868, 98446, 99658, 89224, 90947])