In [2]:
import numpy as np

In [3]:
iris = np.genfromtxt(r"C:\Users\hi\Desktop\Innomatics\Sample Docs for practice\Iris_clean_-_Copy.csv", dtype = 'float32', delimiter=',')
iris

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

In [4]:
iris = iris[1:,:]

In [5]:
iris

array([[5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000e-01],
       [5.700e+00, 3.800e+00, 1.700e+00, 3.000

In [6]:
SepalLengthCm = iris[0:,0]
SepalLengthCm

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [7]:
SepalWidthCm = iris[0:,1]
SepalWidthCm

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [8]:
PetalLengthCm = iris[0:,2]
PetalLengthCm


array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [9]:
PetalWidthCm = iris[0:,3]
PetalWidthCm


array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

# SepalLengthCm

In [10]:
np.nanmean(SepalLengthCm)     ## SepalLengthCm mean

7.5105586

In [11]:
SepalLengthCm[SepalLengthCm>8]

array([ 50. ,  50.4, 116.3,  70.2], dtype=float32)

In [12]:
SepalLengthCm = np.where(SepalLengthCm>8,7.5105586, SepalLengthCm)      ## Replacing outliers of SepalLengthCm
SepalLengthCm

array([5.1      , 4.9      , 4.7      , 4.6      , 7.5105586, 5.4      ,
       4.6      , 5.       , 4.4      , 4.9      , 5.4      , 4.8      ,
       4.8      , 4.3      , 5.8      , 5.7      , 7.5105586, 5.1      ,
       5.7      , 5.1      , 5.4      , 5.1      , 4.6      , 5.1      ,
       4.8      , 5.       , 5.       , 5.2      , 5.2      , 4.7      ,
       4.8      , 5.4      , 5.2      , 5.5      , 4.9      , 5.       ,
       5.5      , 4.9      , 4.4      , 5.1      , 5.       , 4.5      ,
       4.4      , 5.       , 5.1      , 4.8      , 5.1      , 4.6      ,
       5.3      , 5.       , 7.       , 6.4      , 6.9      , 5.5      ,
       6.5      , 5.7      , 7.5105586, 4.9      , 6.6      , 5.2      ,
       5.       , 5.9      , 6.       , 6.1      , 5.6      , 6.7      ,
       5.6      , 5.8      , 6.2      , 5.6      , 5.9      , 6.1      ,
       6.3      , 6.1      , 6.4      , 6.6      , 6.8      , 6.7      ,
       6.       , 5.7      , 5.5      , 5.5      , 

In [16]:
SepalLengthCm = np.where(np.isnan(SepalLengthCm),7.5105586,SepalLengthCm)

## Replacing missing values of SepalLengthCm and converting to int32

SepalLengthCm = SepalLengthCm.astype('int32')
SepalLengthCm

array([5, 4, 4, 4, 7, 5, 4, 5, 4, 4, 5, 4, 4, 4, 5, 5, 7, 5, 5, 5, 5, 5,
       4, 5, 4, 5, 5, 5, 5, 4, 4, 5, 5, 5, 4, 5, 5, 4, 4, 5, 5, 4, 4, 5,
       5, 4, 5, 4, 5, 5, 7, 6, 6, 5, 6, 5, 7, 4, 6, 5, 5, 5, 6, 6, 5, 6,
       5, 5, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 7, 6, 6, 7, 4, 7, 6, 7,
       6, 6, 6, 5, 5, 6, 6, 7, 7, 6, 6, 5, 7, 6, 6, 7, 6, 6, 6, 7, 7, 7,
       6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 7, 7, 7,
       7, 4, 7, 6, 5, 5, 7, 6, 7, 6, 6])

# SepalWidthCm

In [17]:
np.nanmean(SepalWidthCm)    ## SepalWidthCm  mean

4.7132077

In [18]:
SepalWidthCm = np.where(SepalWidthCm>5,4.7132077,SepalWidthCm)     ## Replacing outliers of SepalWidthCm
SepalWidthCm

array([3.5      , 3.       , 3.2      , 3.1      , 3.6      ,       nan,
       3.4      , 3.4      , 2.9      , 3.1      , 3.7      , 3.4      ,
       4.7132077, 3.       , 4.       , 4.4      ,       nan, 3.5      ,
       3.8      , 3.8      , 3.4      , 3.7      , 3.6      , 3.3      ,
       3.4      , 3.       , 4.7132077, 3.5      , 3.4      , 3.2      ,
       3.1      , 3.4      , 4.1      , 4.2      , 3.1      , 3.2      ,
       3.5      , 3.1      , 3.       , 3.4      , 3.5      , 2.3      ,
       3.2      , 3.5      , 3.8      , 3.       , 3.8      , 3.2      ,
       3.7      , 3.3      , 3.2      , 3.2      ,       nan, 2.3      ,
       2.8      , 2.8      , 3.3      , 2.4      , 2.9      , 2.7      ,
       2.       , 3.       , 2.2      , 2.9      , 2.9      , 3.1      ,
       3.       , 2.7      , 2.2      , 2.5      , 3.2      , 2.8      ,
       2.5      ,       nan, 2.9      , 3.       , 2.8      , 3.       ,
       2.9      , 2.6      , 2.4      , 2.4      , 

In [19]:
SepalWidthCm = np.where(np.isnan(SepalWidthCm),4.7132077,SepalWidthCm) 

## Replacing missing values of SepalWidthCm and converting to int32
SepalWidthCm = SepalWidthCm.astype('int32')
SepalWidthCm

array([3, 3, 3, 3, 3, 4, 3, 3, 2, 3, 3, 3, 4, 3, 4, 4, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 3,
       3, 2, 2, 2, 3, 2, 2, 4, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
       3, 2, 2, 3, 4, 2, 2, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 3, 2, 2, 2, 3,
       3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 2, 2, 3, 3, 2, 3, 2, 3, 2, 3,
       2, 2, 2, 3, 3, 4, 3, 3, 3, 3, 2, 3, 3, 4, 2, 3, 3, 3, 2, 2, 2, 3,
       3, 2, 2, 2, 3, 2, 2, 2, 3, 3, 2])

# PetalLengthCm

In [20]:
np.nanmean(PetalLengthCm)      ## PetalLengthCm mean

4.022641

In [21]:
PetalLengthCm = np.where(PetalLengthCm>6,4.022641,PetalLengthCm)  ## Replacing outliers for PetalLengthCm
PetalLengthCm

array([1.4     , 1.4     , 1.3     , 1.5     , 1.4     , 1.7     ,
       1.4     , 1.5     , 1.4     ,      nan, 1.5     , 1.6     ,
       1.4     , 1.1     , 1.2     , 1.5     , 1.3     , 1.4     ,
       1.7     , 1.5     , 1.7     , 1.5     , 1.      , 1.7     ,
       1.9     , 1.6     , 1.6     , 1.5     , 1.4     , 1.6     ,
       1.6     , 1.5     , 1.5     , 1.4     , 1.5     , 1.2     ,
       1.3     , 1.5     , 1.3     , 1.5     , 1.3     , 4.022641,
       1.3     , 1.6     , 1.9     , 1.4     , 1.6     , 1.4     ,
       1.5     , 1.4     , 4.7     , 4.5     , 4.9     , 4.      ,
       4.6     , 4.5     , 4.7     , 3.3     , 4.6     , 3.9     ,
       3.5     , 4.2     , 4.      , 4.7     , 3.6     , 4.4     ,
       4.5     , 4.1     , 4.5     , 3.9     , 4.8     , 4.      ,
       4.9     , 4.7     , 4.3     , 4.4     , 4.8     , 5.      ,
       4.5     , 3.5     , 4.022641, 3.7     , 3.9     , 5.1     ,
       4.5     , 4.5     , 4.7     , 4.4     , 4.1     , 4.   

In [22]:
PetalLengthCm = np.where(np.isnan(PetalLengthCm),4.022641,PetalLengthCm)  

## Replacing missing values for PetalLengthCm and converting to int32
PetalLengthCm = PetalLengthCm.astype('int32')
PetalLengthCm

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1,
       1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 4, 4, 3, 4,
       4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 5, 4, 3, 4, 3, 3, 5, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 6, 5, 5, 5, 5, 4, 4, 4, 5, 4,
       5, 5, 4, 5, 5, 5, 5, 4, 4, 5, 5, 4, 4, 4, 5, 6, 4, 4, 5, 5, 4, 4,
       5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 4, 4, 5,
       6, 4, 4, 5, 5, 4, 4, 4, 4, 5, 5])

# PetalWidthCm

In [23]:
np.nanmean(PetalWidthCm)      ## PetalWidthCm Mean

2.810909

In [25]:
PetalWidthCm = np.where(PetalWidthCm>3,2.810909,PetalWidthCm)    

## Replacing outliers of PetalWidthCm and converting to int32
PetalWidthCm = PetalWidthCm.astype('int32')
PetalWidthCm

array([0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2,
       2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1])

In [26]:
np.sum(np.isnan(PetalWidthCm))        ## No missing values for PetalWidthCm

0

# Q2) Mean Of sepal length

In [27]:
np.mean(SepalLengthCm)            ## Mean of sepal length after replacing outliers and missing values

5.484848484848484

# Q3) sort the sepal width in ascending order

In [28]:
np.sort(SepalWidthCm)           

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

# Q4)apply all statistical measures on  sepal width and length

In [ ]:
## Median

In [29]:
np.median(SepalLengthCm)

5.0

In [30]:
np.median(SepalWidthCm)

3.0

In [93]:
## Mean

In [31]:
np.mean(SepalLengthCm)

5.484848484848484

In [32]:
np.mean(SepalWidthCm)

2.684848484848485

In [97]:
## Standard Deviation

In [33]:
np.std(SepalLengthCm)

0.8985244510665087

In [34]:
np.std(SepalWidthCm)

0.6110702048250897

In [100]:
## Variance

In [35]:
np.var(SepalLengthCm)

0.8073461891643708

In [36]:
np.var(SepalWidthCm)

0.37340679522497705

In [104]:
## Minimum

In [37]:
np.min(SepalLengthCm)

4

In [38]:
np.min(SepalWidthCm)

2

In [ ]:
## Maximum

In [39]:
np.max(SepalLengthCm)

7

In [40]:
np.max(SepalWidthCm)

4

In [110]:
## Range

In [41]:
range_of_len = np.max(SepalLengthCm) - np.min(SepalLengthCm)
range_of_len

3

In [42]:
range_of_wid = np.max(SepalWidthCm) - np.min(SepalWidthCm)
range_of_wid

2

# Q5) after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [59]:
new_iris = np.array([SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm]).reshape(4,165)

In [62]:
np.savetxt("cleaned_iris.txt",new_iris)

In [65]:
np.loadtxt("cleaned_iris.txt")

array([[5., 4., 4., 4., 7., 5., 4., 5., 4., 4., 5., 4., 4., 4., 5., 5.,
        7., 5., 5., 5., 5., 5., 4., 5., 4., 5., 5., 5., 5., 4., 4., 5.,
        5., 5., 4., 5., 5., 4., 4., 5., 5., 4., 4., 5., 5., 4., 5., 4.,
        5., 5., 7., 6., 6., 5., 6., 5., 7., 4., 6., 5., 5., 5., 6., 6.,
        5., 6., 5., 5., 6., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6., 5.,
        5., 5., 5., 6., 5., 6., 6., 6., 5., 5., 5., 6., 5., 5., 5., 5.,
        5., 6., 5., 5., 6., 5., 7., 6., 6., 7., 4., 7., 6., 7., 6., 6.,
        6., 5., 5., 6., 6., 7., 7., 6., 6., 5., 7., 6., 6., 7., 6., 6.,
        6., 7., 7., 7., 6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 5., 6.,
        6., 6., 6., 6., 6., 5., 5., 7., 7., 7., 7., 4., 7., 6., 5., 5.,
        7., 6., 7., 6., 6.],
       [3., 3., 3., 3., 3., 4., 3., 3., 2., 3., 3., 3., 4., 3., 4., 4.,
        4., 3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 3., 3., 3., 3., 3.,
        4., 4., 3., 3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3., 4., 2., 2.,