### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

In [2]:
import numpy as np

In [44]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [45]:
np.sum(np.isnan(marks))         ## There are 4 missing values

4

In [46]:
outliers = ((marks<20) | (marks>100))      ## Assuming  as passing marks as 20 and 100 as total marks of subject, there are 8 outliers
np.sum(outliers)

7

In [47]:
marks = (np.where(np.isnan(marks),87,marks).astype('int16'))       ## Missing values replaced with 87
marks

array([ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
        87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
         2,  53,  44], dtype=int16)

In [48]:
marks = (np.where(outliers,45, marks).astype('int16'))         ## Outliers are replaced with 45
marks

array([44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87, 45, 56, 81,
       59, 45, 92, 87, 87, 96, 97, 45, 45, 45, 53, 44], dtype=int16)

In [49]:
average_marks = np.mean(marks)        ## Average marks of students
average_marks

62.310344827586206

In [50]:
less_60 = np.sum(marks<60)     ## No.of students less than 60
less_60

18

In [51]:
maximum = np.max(marks)      ## Maximum marks
maximum

97

In [52]:
marks.dtype

dtype('int16')

In [53]:
marks = marks.astype('float32')   ## Converted marks to 'float32'
marks.dtype

dtype('float32')

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


In [57]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b = np.array([10,5,12])
np.linalg.solve(a,b)

array([-7.36952666e+15,  7.36952666e+15,  7.36952666e+15])

In [55]:
## from above equation x = -7.36952666e+15, y =7.36952666e+15 , z= 7.36952666e+15

In [56]:
c = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
d = np.array([8,1,7,3])
np.linalg.solve(c,d)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [58]:
## from above equation x = 1.73170732, y = -0.75609756, z = -3.46341463, w = 0.6097561

In [59]:
e = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
f = np.array([10,-3,4])
np.linalg.solve(e,f)

array([2.85365854, 0.6097561 , 0.87804878])

In [60]:
## from above equation x = 2.85365854, y = 0.6097561 ,z = 0.87804878

### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

In [61]:
A = np.random.randint(1,100,10)         ## 10 random numbers between 1,100
A

array([63, 18, 55, 43, 54,  6, 97,  4, 33, 28])

In [63]:
A[np.where(A>50)]        ## Elements in A greater than 50

array([63, 55, 54, 97])

In [65]:
B = A[np.where(A>50)]       ## Assigning above condition to B
B

array([63, 55, 54, 97])

In [68]:
print("Mean of B: ",np.mean(B))
print("Array A: ",A)
print("Array B: ",B)

Mean of B:  67.25
Array A:  [63 18 55 43 54  6 97  4 33 28]
Array B:  [63 55 54 97]


### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

In [72]:
C = np.random.randint(-10,10,16).reshape(4,4)   ## 4x4 matrix between -10 and 10
C

array([[  9,  -3,   2,  -3],
       [ -7, -10,  -5,   1],
       [  8,   8,   3,  -2],
       [ -8,  -2, -10,  -3]])

In [73]:
c = np.where(C<0,0,C)         ## Replaced negative values with 0
c

array([[9, 0, 2, 0],
       [0, 0, 0, 1],
       [8, 8, 3, 0],
       [0, 0, 0, 0]])

In [80]:
print(f"Original C: \n{C}\n\nModified C: \n{c}")

Original C: 
[[  9  -3   2  -3]
 [ -7 -10  -5   1]
 [  8   8   3  -2]
 [ -8  -2 -10  -3]]

Modified C: 
[[9 0 2 0]
 [0 0 0 1]
 [8 8 3 0]
 [0 0 0 0]]
