In [1]:
import numpy as np

Q1)  Creating array in diff methods

In [2]:
arr = np.array([10,12,15,24,59,78])          ## Method 1
arr

array([10, 12, 15, 24, 59, 78])

In [3]:
list1 = [10,12,15,24,59,78]              ## Method 2
arr1 = np.array(list1)
arr1

array([10, 12, 15, 24, 59, 78])

In [4]:
tup = (10,12,15,24,59,78)           ## Method 3
arr2 = np.array(tup)
arr2

array([10, 12, 15, 24, 59, 78])

In [5]:
np.arange(1,10)                 ## Method 4 for Regular spaced

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(40,50,10)          ## Method 5 for evenly spaced

array([40.        , 41.11111111, 42.22222222, 43.33333333, 44.44444444,
       45.55555556, 46.66666667, 47.77777778, 48.88888889, 50.        ])

**1D NumPy Array for 12 positive int**

In [8]:
array1 = np.arange(1,13)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**1D NumPy Array for 20 elements between 0 and 12**

In [9]:
array2 = np.linspace(0,12,20)
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

**Attributes of Array 1**

In [11]:
array1.dtype

dtype('int32')

In [15]:
array1.ndim

1

In [16]:
array1.size

12

In [17]:
array1.itemsize

4

In [19]:
array1.nbytes

48

**Attributes of Array 2**

In [20]:
array2.dtype

dtype('float64')

In [21]:
array2.ndim

1

In [22]:
array2.size

20

In [23]:
array2.itemsize

8

In [24]:
array2.nbytes

160

# Statistics method

**Array1**

In [27]:
np.mean(array1)

6.5

In [29]:
np.median(array1)

6.5

In [30]:
np.min(array1)

1

In [31]:
np.max(array1)

12

In [36]:
np.max(array1) - np.min(array1)        ## Range

11

In [34]:
np.var(array1)             ## Variance

11.916666666666666

In [37]:
np.std(array1)            ## standard Dev

3.452052529534663

**Array 2**

In [39]:
np.mean(array2)

5.999999999999999

In [40]:
np.median(array2)

6.0

In [41]:
np.min(array2)

0.0

In [42]:
np.max(array2)

12.0

In [43]:
np.max(array2) - np.min(array2)        ## Range

12.0

In [44]:
np.var(array2)             ## Variance

13.26315789473684

In [45]:
np.std(array2)            ## standard Dev

3.6418618720013036

**IQR for Array 1**


In [46]:
Q1=np.percentile(array1,25)
Q1

3.75

In [48]:
Q3=np.percentile(array1,75)
Q3

9.25

In [49]:
IQR = Q3-Q1               ## IQR
IQR

5.5

In [50]:
lower = Q1 - (1.5*IQR)          ## lower limit
lower

-4.5

In [51]:
upper = Q3 + (1.5*IQR)       ## upper limit
upper

17.5

**IQR for array 2**

In [52]:
Q1=np.percentile(array2,25)
Q1

3.0

In [53]:
Q3=np.percentile(array2,75)
Q3

9.0

In [54]:
IQR = Q3-Q1               ## IQR
IQR

6.0

In [55]:
lower = Q1 - (1.5*IQR)          ## lower limit
lower

-6.0

In [56]:
upper = Q3 + (1.5*IQR)       ## upper limit
upper

18.0